server:
  port: 8081
  servlet:
    context-path: /quick-grade

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG

spring:
  application:
    name: quick-grade

secret-key: ${SECRET_KEY}